#!/bin/bash

echo "🚀 Setting up Supabase PostgreSQL for WisdomOS"
echo ""
echo "📋 Follow these steps:"
echo ""
echo "1️⃣  Create a Supabase Account (if you don't have one):"
echo "    → Go to https://supabase.com"
echo "    → Sign up with GitHub or Email"
echo ""
echo "2️⃣  Create a New Project:"
echo "    → Click 'New Project'"
echo "    → Project name: wisdomos-database"
echo "    → Database Password: [Generate a strong password - SAVE THIS!]"
echo "    → Region: Choose closest to you"
echo "    → Click 'Create new project'"
echo "    → Wait 1-2 minutes for setup"
echo ""
echo "3️⃣  Get Your Database Connection String:"
echo "    → Go to Settings (gear icon)"
echo "    → Click on 'Database' in the sidebar"
echo "    → Scroll to 'Connection string'"
echo "    → Click on 'URI' tab"
echo "    → Copy the connection string"
echo ""
echo "4️⃣  Add to Vercel Environment Variables:"
echo ""
echo "    Run this command with your connection string:"
echo "    vercel env rm DATABASE_URL production"
echo "    echo 'YOUR_CONNECTION_STRING' | vercel env add DATABASE_URL production"
echo ""
echo "5️⃣  Switch to PostgreSQL Schema:"
cp prisma/schema.postgresql.prisma prisma/schema.prisma
echo "    ✅ Switched to PostgreSQL schema"
echo ""
echo "6️⃣  Initialize Database (after adding DATABASE_URL to Vercel):"
echo "    export DATABASE_URL='YOUR_CONNECTION_STRING'"
echo "    npx prisma db push"
echo "    npx prisma db seed"
echo ""
echo "7️⃣  Redeploy to Vercel:"
echo "    vercel --prod --yes"
echo ""
echo "📝 Example connection string format:"
echo "postgresql://postgres:[YOUR-PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres"
echo ""
echo "🎉 Your app will be fully functional at:"
echo "https://wisdomos-web.vercel.app"