# Railway configuration for wisdomos-api repository
[build]
  builder = "NIXPACKS"
  buildCommand = "pnpm install && pnpm run build"

[deploy]
  startCommand = "pnpm run start:prod"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 300
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production]
  name = "wisdomos-api-production"
  
  [environments.production.variables]
    NODE_ENV = "production"
    PORT = "3000"
    
[environments.staging]
  name = "wisdomos-api-staging"
  
  [environments.staging.variables]
    NODE_ENV = "staging" 
    PORT = "3000"

# Service configuration
[services]
  
  [[services.api]]
    name = "wisdomos-api"
    port = 3000
    
    # Auto-scaling configuration
    [services.api.autoscaling]
      enabled = true
      minReplicas = 1
      maxReplicas = 5
      targetCPUUtilization = 70
      targetMemoryUtilization = 80
    
    # Resource limits
    [services.api.resources]
      requests.cpu = "0.1"
      requests.memory = "256Mi"
      limits.cpu = "1.0"
      limits.memory = "1Gi"
      
    # Health checks
    [services.api.healthcheck]
      path = "/api/health"
      intervalSeconds = 30
      timeoutSeconds = 10
      successThreshold = 1
      failureThreshold = 3

# Database connection
[[services.database]]
  name = "postgres"
  plan = "$5"
  
  [services.database.variables]
    POSTGRES_DB = "wisdomos"
    POSTGRES_USER = "wisdomos"

# Redis for caching (optional)
[[services.redis]]
  name = "redis"
  plan = "$3"