# Netlify configuration for wisdomos-web repository
[build]
  base = "."
  command = "pnpm install && pnpm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"
  PNPM_VERSION = "8.15.0"
  NODE_ENV = "production"

[context.production]
  command = "pnpm install && pnpm run build"
  
[context.deploy-preview]
  command = "pnpm install && pnpm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API proxy to separate API deployment
[[redirects]]
  from = "/api/*"
  to = "https://wisdomos-api.railway.app/api/:splat"
  status = 200
  headers = {X-From = "Netlify"}

# Client-side routing fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://analytics.google.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://wisdomos-api.railway.app https://*.supabase.co wss://*.supabase.co;"

# Cache optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Environment-specific redirects
[context.production.environment]
  NEXT_PUBLIC_API_BASE = "https://wisdomos-api.railway.app"
  NEXT_PUBLIC_SITE_URL = "https://wisdomos.netlify.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_BASE = "https://wisdomos-api-staging.railway.app"
  NEXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--wisdomos.netlify.app"