version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: wisdomos-db
    environment:
      POSTGRES_DB: wisdomos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - wisdomos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: wisdomos-redis
    volumes:
      - redis_data:/data
    networks:
      - wisdomos-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: wisdomos-backend
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:-postgres}@db:5432/wisdomos?schema=public
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-https://wisdomos-phoenix.vercel.app}
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - wisdomos-network
    restart: unless-stopped

networks:
  wisdomos-network:
    driver: bridge

volumes:
  db_data:
  redis_data: